Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: lambda.ImageResizeHandler
      CodeUri: C:\Users\PC\IdeaProjects\AWS\AWS_Lambda
      Runtime: java11
      Architectures:
        - x86_64